server:
    context-path: /account
    port: 8088
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

application:
    fileLocation: account.json